FinlayWagg.lyHost/Models/ErrorViewModel.cs
namespace FinlayWagg.lyHost.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinlayWagg.lyHost/Models/TableColumns.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
/* The data gathering info including database column name and display data as well as the Key being 'ID' */
namespace FinlayWagg.lyHost.Models
{
    public class TableColumns
    {
        [Key]
        public int Id { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Date")]
        public DateTime LeadDate { get; set; }

        public string Name { get; set; }
        [DisplayName("Dog Owner or Walker (If You're an Owner Please Enter 'Owner of <Dogs Name> a <Dogs Breed>')")]
        public string WalkerOrOwner { get; set; }
        [DisplayName("Client Contact Email")]
        public string Email { get; set; }
        [DisplayName("Suggested Walk Time (Minutes)")]
        public string SuggestedWalkTime { get; set; }
    }
}

FinlayWagg.lyHost/Controllers/HomeController.cs
using FinlayWagg.lyHost.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FinlayWagg.lyHost.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinlayWagg.lyHost/Controllers/TableColumnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinlayWagg.lyHost.Data;
using FinlayWagg.lyHost.Models;

namespace FinlayWagg.lyHost.Controllers
{
    public class TableColumnsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TableColumnsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TableColumns
        public async Task<IActionResult> Index()
        {
            return View(await _context.WalkingData.ToListAsync());
        }

        // GET: TableColumns/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tableColumns = await _context.WalkingData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tableColumns == null)
            {
                return NotFound();
            }

            return View(tableColumns);
        }

        // GET: TableColumns/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TableColumns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LeadDate,Name,WalkerOrOwner,Email,SuggestedWalkTime")] TableColumns tableColumns)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tableColumns);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tableColumns);
        }

        // GET: TableColumns/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tableColumns = await _context.WalkingData.FindAsync(id);
            if (tableColumns == null)
            {
                return NotFound();
            }
            return View(tableColumns);
        }

        // POST: TableColumns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LeadDate,Name,WalkerOrOwner,Email,SuggestedWalkTime")] TableColumns tableColumns)
        {
            if (id != tableColumns.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tableColumns);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TableColumnsExists(tableColumns.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tableColumns);
        }

        // GET: TableColumns/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tableColumns = await _context.WalkingData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tableColumns == null)
            {
                return NotFound();
            }

            return View(tableColumns);
        }

        // POST: TableColumns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tableColumns = await _context.WalkingData.FindAsync(id);
            if (tableColumns != null)
            {
                _context.WalkingData.Remove(tableColumns);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TableColumnsExists(int id)
        {
            return _context.WalkingData.Any(e => e.Id == id);
        }
    }
}

FinlayWagg.lyHost/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@* Welcome info *@
<div class="text-center">
    <h1 class="display-4">Welcome to Wagg.ly</h1>
    <p>Register for free today and meet dog owners and walkers in your local area! Find the best solution for you.</p>
</div>

FinlayWagg.lyHost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinlayWagg.lyHost</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinlayWagg.lyHost.styles.css" asp-append-version="true" />
</head>
<body>
    @* The mapped layout for the main page including the header and buttons *@
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wagg.ly</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TableColumns" asp-action="Index">Register Here</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* footer which is alway present like the header with shortcut to the about us page *@
        <div class="container">
            &copy; 2024 - Wagg.ly - <a asp-area="" asp-controller="Home" asp-action="Privacy">About us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FinlayWagg.lyHost/Views/TableColumns/Create.cshtml
@model FinlayWagg.lyHost.Models.TableColumns

@{
    ViewData["Title"] = "Create";
}

<h1>Register</h1>

<h4>TableColumns</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LeadDate" class="control-label"></label>
                <input asp-for="LeadDate" class="form-control" />
                <span asp-validation-for="LeadDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WalkerOrOwner" class="control-label"></label>
                <input asp-for="WalkerOrOwner" class="form-control" />
                <span asp-validation-for="WalkerOrOwner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuggestedWalkTime" class="control-label"></label>
                <input asp-for="SuggestedWalkTime" class="form-control" />
                <span asp-validation-for="SuggestedWalkTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@* Function creates a new entry within the database using the 'ID' as key the submit button sends the data to the store *@
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinlayWagg.lyHost/Views/TableColumns/Delete.cshtml
@model FinlayWagg.lyHost.Models.TableColumns

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TableColumns</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeadDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeadDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WalkerOrOwner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WalkerOrOwner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuggestedWalkTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuggestedWalkTime)
        </dd>
    </dl>
    @* Function identifies the registration in the database via the key (ID) and removes the selected row *@
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinlayWagg.lyHost/Views/TableColumns/Details.cshtml
@model FinlayWagg.lyHost.Models.TableColumns

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
@* Function identifies the registration in the database via the key (ID) and allows the user to view it in full with the option to edit or delete it *@
<div>
    <h4>TableColumns</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeadDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeadDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WalkerOrOwner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WalkerOrOwner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuggestedWalkTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuggestedWalkTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FinlayWagg.lyHost/Views/TableColumns/Edit.cshtml
@model FinlayWagg.lyHost.Models.TableColumns

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TableColumns</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="LeadDate" class="control-label"></label>
                <input asp-for="LeadDate" class="form-control" />
                <span asp-validation-for="LeadDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WalkerOrOwner" class="control-label"></label>
                <input asp-for="WalkerOrOwner" class="form-control" />
                <span asp-validation-for="WalkerOrOwner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuggestedWalkTime" class="control-label"></label>
                <input asp-for="SuggestedWalkTime" class="form-control" />
                <span asp-validation-for="SuggestedWalkTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@* Function identifies the registration in the database via the key (ID) and updates the selected row with the updated response *@
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinlayWagg.lyHost/Views/TableColumns/Index.cshtml
@model IEnumerable<FinlayWagg.lyHost.Models.TableColumns>

@{
    ViewData["Title"] = "Index";
}

<h1>Wagg.ly Signup Page</h1>

<p>
    <a asp-action="Create">+ Register Here</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LeadDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WalkerOrOwner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SuggestedWalkTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LeadDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WalkerOrOwner)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SuggestedWalkTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>